### PR TITLE
lavc/mjpegdec: avoid printing useless message in default log level

### PR DESCRIPTION
**Pull request by fritsch**
The change of bps from 0 doesn't contain any info useful to the
user. This message is now at info log level only if the original
value is !=0, otherwise pushed back to debug log level. The
original value is displayed additionally.

Signed-off-by: Moritz Barsnick <barsnick@gmx.net>
Signed-off-by: Michael Niedermayer <michael@niedermayer.cc>

### CODE REVIEW

**Comment by fritsch** [comment]
@FernetMenta this avoids verbose printing for every jpeg picture that we are loading. Okay?

>13:51:06 T:18446744072036535184    INFO: ffmpeg[9C47CB90]: [mjpeg] Changing bps to 8
551	13:51:06 T:18446744072040233872    INFO: ffmpeg[9C803B90]: [mjpeg] Changing bps to 8
552	13:51:06 T:18446744072036535184    INFO: ffmpeg[9C47CB90]: [mjpeg] Changing bps to 8
553	13:51:06 T:18446744072040233872    INFO: ffmpeg[9C803B90]: [mjpeg] Changing bps to 8
554	13:51:06 T:18446744072036535184    INFO: ffmpeg[9C47CB90]: [mjpeg] Changing bps to 8

**Comment by FernetMenta** [comment]
hmm, looks not like a mission critical patch. Remember that the goal is still to get rid of this fork. Pulling rather unimportant patches set IMO a wring signal.

This looks similar to the log spam generated by the thumb loader. I think we should look to a method to turn those off while keeping ffmpeg messages for the player.

**Comment by fritsch** [comment]
Yeah, that's an alternative approach, will have a look.

**Comment by fritsch** [comment]
Closed in favor of @FernetMenta FFMPeg Logger rework. Thanks much.

**Pull request closed without merging**
