### PR TITLE
libavformat/rtspdec: Don't send teardown if rtsp_hd_out is null

### PR DESCRIPTION
**Pull request by phunkyfish**
Fix for RTSP streams from https://github.com/xbmc/xbmc/pull/16395#issuecomment-517924521

Patch submitted upstream: https://patchwork.ffmpeg.org/patch/14239/

Will be required for kodi 18.4

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Thanks, fix is working perfectly! Will include it in nightly test builds until merged.

**Comment by MilhouseVH** [comment]
This PR seems to have gone tits up.

**Comment by FernetMenta** [comment]
> This PR seems to have gone tits up.

you mean like the several hundred dying PRs on this project? same happens on Linux kernel. you need to go after it and poke the folks actively to get attention.

**Comment by MilhouseVH** [comment]
No I mean it looks like it's been re-based incorrectly - yesterday it had one commit (https://github.com/xbmc/FFmpeg/compare/1b8704b88fecf36...78dc34ba1419b47) but now it has 8 commits and no longer applies cleanly on top of the unpacked 4.0.3-Leia-18.2 tarball (when using GNU patch).

**Comment by phunkyfish** [comment]
This PR was not rebased. Another change must have happened causing this. Will look at this later and fix it.

On the upstream I have been following up on the patch.

**Comment by phunkyfish** [comment]
I have no idea what happened but it's fixed now.

I wonder was the tarball changed?

**Comment by phunkyfish** [comment]
This should be ok to merge if someone could do the honours.

**Comment by MilhouseVH** [comment]
Thanks! :)

**Comment by MilhouseVH** [comment]
> I wonder was the tarball changed?

No, the tarball is unchanged - it was only this PR that acquired several new and very old commits for some reason.

**Comment by phunkyfish** [comment]
But weirdly those commits were already in the branch. Who knows

**Comment by fritsch** [comment]
I will merge this PR in two hours. If there are other patches, already sent upstream and need to be included, please ping me.

I will rebase on ffmpeg 4.0 branch afterwards so that we can bump it in master and also in Leia. There is currently no new ffmpeg 4.0.x release newer than 4.0.4 but the 4.0.x branch already includes several fixes that are important for kodi's usecases:

among others:
https://github.com/FFmpeg/FFmpeg/commit/82e1fb864b37a03b63aa43456d0b9f744bb409f5
https://github.com/FFmpeg/FFmpeg/commit/1687b067dd5879034388a6c03f79619586918b7e
and three more aac fixes.

**Pull request merged**
