### PR TITLE
Fix HLS with HTTP Cookie Authentication

### PR DESCRIPTION
**Pull request by micahg**
Hi,

I made some changes to fix HLS streams with cookie authentication. In FFMPEG they were broken and didn't work in Kodi 17 as a result.

I've fixed them on the FFMPEG master branch and backported them into 3.3 -- I wanted to make sure that they'd get pulled before Kodi 18 was released.

If you're going to do another resync with the 3.3 branch of FFMPEG then you can just close this PR or whatever (it wont be necessary as they're already there).  If not, I'd like for these fixes to get in -- I fixed them with Kodi in mind.

Thanks,

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@micahg v18 is far from ready so it will certainly be several months and we'll regularly rebase ffmpeg 3.3 (or anything later that comes out)

**Comment by micahg** [comment]
OK, I figured as much -- just wasn't sure where to have that conversation. For future reference, where is that place? The forums?

Anyway, I'll just close it and monitor to make sure the fixes get in there eventually.

Thanks,

**Comment by fritsch** [comment]
Thanks for the headsup I just fast forwarded our 3.3-kodi branch to include your changes.

**Comment by Rechi** [comment]
You can talk with us in the #kodi-dev channel at freenode.net.

**Comment by fritsch** [comment]
Will rebase again once 3.3.2 is out and the tag a new build so that kodi nightlies use it - thx again.

**Comment by micahg** [comment]
Alright then -- TYVM everyone.

**Comment by micahg** [comment]
Hi, I think I cleaned everything up properly and I still don't see those changes in. No biggie, I'll check back in a few weeks.

**Comment by MartijnKaijser** [comment]
I see them in our branch

**Comment by fritsch** [comment]
It won't be built with an intree build, you have to build it externally until I have tagged it (will do with 3.3.2 landing) and afterwards bumping in depends for kodi.

**Comment by fritsch** [comment]
@micahg I redid the 3.3.1-Leia-Alpha tag (it was not referenced before) and bumped it in the corresponding build file via: https://github.com/xbmc/xbmc/pull/12241 - after fernet acked it - you can build it as normal.

**Pull request closed without merging**
