### PR TITLE
Implement MatroskaBlockAdditionMapping

### PR DESCRIPTION
**Pull request by quietvoid**
Adds Matroska BlockAdditionMapping elements parsing.
Creates AVDOVIDecoderConfigurationRecord and adds it to track side data.

Taken from Plex's ffmpeg source code, cherry picked the changes.
It's possible the `ff_mov_parse_dvcc_dvvc` function is duplicated in `isom.c`.

Example results:
`[info]     Side data:
[info]       DOVI configuration record: version: 1.0, profile: 8, level: 3, rpu flag: 1, el flag: 0, bl flag: 1, compatibility id: 6`

I'm not too comfortable forwarding the patch to ffmpeg upstream, so feel free.

### CODE REVIEW

**Comment by lrusak** [comment]
Hello and thanks for the contribution!

I really appreciate you taking the time to pull out the changes from the plex ffmpeg source dump.

I would really like this to go upstream so we can track it there. I assume all the code is still licensed under GPL?

Until we track it upstream I don't see us merging this in. Though we people can include it in test builds.

**Comment by quietvoid** [comment]
Yes the code is still licensed under GPL, I haven't made any modifications other than adding the `matroska_block_addition_mapping[5]` declaration.

Hopefully one of you can send it upstream, I just mainly wanted to get attention on this feature, to be able to implement playback in Kodi afterwards.

**Comment by lrusak** [comment]
> Yes the code is still licensed under GPL, I haven't made any modifications other than adding the `matroska_block_addition_mapping[5]` declaration.
> 
> Hopefully one of you can send it upstream, I just mainly wanted to get attention on this feature, to be able to implement playback in Kodi afterwards.

I totally understand. It's too bad the original author hasn't submitted it yet.

**Comment by lrusak** [comment]
some references after talking to some people in #ffmpeg-devel on freenode:

https://www.matroska.org/technical/elements.html

https://professional.dolby.com/siteassets/content-creation/dolby-vision-for-content-creators/dolby_vision_bitstreams_within_the_iso_base_media_file_format_dec2017.pdf

https://datatracker.ietf.org/doc/draft-ietf-cellar-codec/

**Comment by quietvoid** [comment]
I'd see this PR split in 2 patches: one for the new Matroska element handling, the other for the specific dvvc/dvcc cases (including the side data addition).
However, the elements could also be used for other codecs (such as h264), for which there's not much info about practical uses currently.

I'm sorry I can't help much more. Do you want to keep this PR open?
Otherwise, I guess it's just about waiting for someone to work on this.

**Comment by quietvoid** [comment]
Should be 'complete' now, just missing a way to make the `AVDOVIDecoderConfigurationRecord` creation generic across containers.

**Comment by lrusak** [comment]
@quietvoid you should probably squash all the changes together

**Comment by quietvoid** [comment]
Done. Sorry I'm not very good at this.

**Comment by mcd2000** [comment]
Does this code really work?
It has function prototype:
`mkv_parse_block_addition_mappings(AVFormatContext *s, AVStream *st, const MatroskaTrack *track)`
and then it's called like this:
`ret = mkv_parse_block_addition_mappings(st, track, matroska->ctx);`

**Comment by quietvoid** [comment]
That's a mistake on my part.. it's not getting merged anyways.
Don't even know if this PR should stay opened, it's basically just a reference for anyone wanting to upstream to ffmpeg.

**Comment by quietvoid** [comment]
I'm gonna close this because 4.4 is out. I made a tag for 4.4 builds: https://github.com/quietvoid/FFmpeg/releases/tag/4.4-MatroskaDovi

I probably won't open another PR unless it's useful.

**Pull request closed without merging**
