### PR TITLE
FFmpeg patches for AV1 10-bit film grain content

### PR DESCRIPTION
**Pull request by a1rwulf**
The patches in this PR have been applied upstream to the 4.4 branch recently.
They are needed to support proper 10bit AV1 playback via VAAPI.

### CODE REVIEW

**Comment by a1rwulf** [comment]
This is not enough, we need more patches from ffmpeg 4.4.

**Comment by fuzzard** [comment]
Maybe look to bump to the 4.4.1 release. If it's not in there it must be in the 5 tree, so you'd need to backport

**Comment by a1rwulf** [comment]
Yeah we could rebase onto 4.4.1 and most likely then I can pick the av1 improvements.
I'll have a look at that.

**Comment by a1rwulf** [comment]
OK, confirmed.
If we rebase our ffmpeg on upstream's 4.4.1 and I pick the needed av1 patches, it works correctly.
@lrusak what's needed to rebase our version on 4.4.1?

Sidenote:
Seems ffmpeg will release 5.0 soon anyway, question is if we go ffmpeg 5.0 for Nexus?

**Comment by lrusak** [comment]
I've rebased the 4.4 branch on 4.4.1 release https://github.com/xbmc/FFmpeg/tree/release/4.4-kodi

**Comment by a1rwulf** [comment]
> I've rebased the 4.4 branch on 4.4.1 release https://github.com/xbmc/FFmpeg/tree/release/4.4-kodi

Thanks!!
Now https://github.com/xbmc/FFmpeg/pull/23 makes AV1 work correctly.

**Pull request closed without merging**
