### PR TITLE
DSF: Upstream picks

### PR DESCRIPTION
**Pull request by fritsch**
Picked from upstream - should fix: https://forum.kodi.tv/showthread.php?tid=338422&pid=2800444

Please wait until user reported back

### CODE REVIEW

**Comment by fritsch** [comment]
@Rechi @FernetMenta fixes: https://forum.kodi.tv/showthread.php?tid=338422 - do we want to take it?

**Comment by Rechi** [comment]
In general I don't like adding patches on top, but as it is in upstream version 4.1 it's fine for me.

Maybe ask the FFmpeg devs to backport the changes to 4.0.

**Comment by FernetMenta** [comment]
> Maybe ask the FFmpeg devs to backport the changes to 4.0.

I agree. They might had a reason why they did not backport it.

**Comment by fritsch** [comment]
@richardpl Sorry for disturbing you. Do you think it is safe to backport (cherry-pick) these patches to the 4.0 branch of ffmpeg? It fixes one bug a user of us has. We plan to ship ffmpeg 4.0 based kodi for the v18 release and are quite late in the cycle. Therefore we don't want to cause other regressions.

Looking at the code it seems entirely safe / separated for me, but your author's opinion is important here to us!

**Comment by richardpl** [comment]
I pushed it to 4.0

**Comment by fritsch** [comment]
Thank you very much!
@FernetMenta @Rechi rebase a final time prior to release?

**Comment by FernetMenta** [comment]
Personally I won't rebase on a non-release branch fo a minor issue. I would rebase on 4.0.4 when released even if this is after Kodi v18 release date. Then the fix will be in 18.1. 
That's my opinion, you can do differently.

**Comment by fritsch** [comment]
Totally fine. I don't have the time to fix regressions and therefore i am asking those questions.
So then let's update when 4.0.4 is out.

**Comment by fritsch** [comment]
Fixed - as it was integrated already.

**Pull request closed without merging**
